export const mockedData = [
  {
    id: 1,
    userId: 1,
    title: "Grocery List",
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    created_at: "2023-04-01T12:00:00Z",
  },
  {
    id: 2,
    userId: 1,
    title: "ToDo for Project",
    body: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undo",
    created_at: "2023-04-02T15:30:00Z",
  },
  {
    id: 3,
    userId: 2,
    title: "Books to Read",
    body: "The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    created_at: "2023-04-03T18:45:00Z",
  },
  {
    id: 4,
    userId: 3,
    title: "Workout Routine",
    body: "Monday: Chest, Tuesday: Back, Wednesday: Rest, Thursday: Arms, Friday: Legs",
    created_at: "2023-04-04T06:00:00Z",
  },
  {
    id: 5,
    userId: 2,
    title: "Meeting Notes",
    body: "Discuss quarterly goals, Review project timelines, Plan team building activity",
    created_at: "2023-04-05T09:20:00Z",
  },
  {
    id: 6,
    userId: 1,
    title: "Grocery List",
    body: "Milk, Eggs, Bread, Butter",
    created_at: "2023-04-01T12:00:00Z",
  },
  {
    id: 7,
    userId: 1,
    title: "ToDo for Project",
    body: "Finish the report, Call the client, Email the presentation",
    created_at: "2023-04-02T15:30:00Z",
  },
  {
    id: 8,
    userId: 2,
    title: "Books to Read",
    body: "The Great Gatsby, War and Peace, To Kill a Mockingbird",
    created_at: "2023-04-03T18:45:00Z",
  },
  {
    id: 9,
    userId: 3,
    title: "Workout Routine",
    body: "Monday: Chest, Tuesday: Back, Wednesday: Rest, Thursday: Arms, Friday: LegsMonday: Chest, Tuesday: Back, Wednesday: Rest, Thursday: Arms, Friday: LegsMonday: Chest, Tuesday: Back, Wednesday: Rest, Thursday: Arms, Friday: Legs",
    created_at: "2023-04-04T06:00:00Z",
  },
  {
    id: 10,
    userId: 2,
    title: "Meeting Notes",
    body: "Discuss quarterly goals, Review project timelines, Plan team building activityDiscuss quarterly goals, Review project timelines, Plan team building activityDiscuss quarterly goals, Review project timelines, Plan team building activity",
    created_at: "2023-04-05T09:20:00Z",
  },
];
