export const mockedData = [
  {
    id: 1,
    userId: 1,
    title: "Grocery List",
    body: "Milk, Eggs, Bread, Butter",
    created_at: "2023-04-01T12:00:00Z",
  },
  {
    id: 2,
    userId: 1,
    title: "ToDo for Project",
    body: "Finish the report, Call the client, Email the presentation",
    created_at: "2023-04-02T15:30:00Z",
  },
  {
    id: 3,
    userId: 2,
    title: "Books to Read",
    body: "The Great Gatsby, War and Peace, To Kill a Mockingbird",
    created_at: "2023-04-03T18:45:00Z",
  },
  {
    id: 4,
    userId: 3,
    title: "Workout Routine",
    body: "Monday: Chest, Tuesday: Back, Wednesday: Rest, Thursday: Arms, Friday: Legs",
    created_at: "2023-04-04T06:00:00Z",
  },
  {
    id: 5,
    userId: 2,
    title: "Meeting Notes",
    body: "Discuss quarterly goals, Review project timelines, Plan team building activity",
    created_at: "2023-04-05T09:20:00Z",
  },
  {
    id: 6,
    userId: 1,
    title: "Grocery List",
    body: "Milk, Eggs, Bread, Butter",
    created_at: "2023-04-01T12:00:00Z",
  },
  {
    id: 7,
    userId: 1,
    title: "ToDo for Project",
    body: "Finish the report, Call the client, Email the presentation",
    created_at: "2023-04-02T15:30:00Z",
  },
  {
    id: 8,
    userId: 2,
    title: "Books to Read",
    body: "The Great Gatsby, War and Peace, To Kill a Mockingbird",
    created_at: "2023-04-03T18:45:00Z",
  },
  {
    id: 9,
    userId: 3,
    title: "Workout Routine",
    body: "Monday: Chest, Tuesday: Back, Wednesday: Rest, Thursday: Arms, Friday: Legs",
    created_at: "2023-04-04T06:00:00Z",
  },
  {
    id: 10,
    userId: 2,
    title: "Meeting Notes",
    body: "Discuss quarterly goals, Review project timelines, Plan team building activity",
    created_at: "2023-04-05T09:20:00Z",
  },
];
